version: '3.7'
services:
  db:
    container_name: abiodoun_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: abiodoun_api
    build: .
    env_file: root/.env
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate && python manage.py collectstatic --no-input
          gunicorn root.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
  nginx:
    container_name: abiodoun_web
    restart: on-failure
    image: staticfloat/nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: "contact@abiodoun.dev"
      ENVSUBST_VARS: api_host
      api_host: "contact@abiodoun.dev"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - ./nginx/mimes.types:/etc/nginx/mime.types:ro
      - static_volume:/code/static
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - api


volumes:
  static_volume:
  postgres_data:
  letsencrypt:
