version: '3.7'
services:
  db:
    container_name: abiodoun_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: abiodoun_api
    build: .
    env_file: root/.env
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate && python manage.py collectstatic --no-input
          gunicorn root.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
  nginx:
    container_name: abiodoun_web
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/user_conf.d
      - ./conf/mimes.types:/etc/nginx/mime.types
      - ./certbot/www:/var/www/certbot/
    depends_on:
      - api
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - .letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email contact@abiodoun.dev --agree-tos -d api.abiodoun.dev
    depends_on:
      - nginx


volumes:
  static_volume:
  postgres_data:
  nginx_secrets:
