version: '3.7'
services:
  db:
    container_name: abiodoun_db
    image: postgres:15-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    container_name: abiodoun_api
    build: .
    env_file: root/.env
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate && python manage.py collectstatic --no-input
          gunicorn root.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
  nginx:
    container_name: abiodoun_web
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/mimes.types:/etc/nginx/mime.types
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - static_volume:/code/static
    depends_on:
      - api
      - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: revoke --cert-path /etc/letsencrypt/live/api.abiodoun.dev/fullchain.pem


volumes:
  static_volume:
  postgres_data:
  nginx_secrets:
