# Generated by Django 3.0 on 2022-01-17 10:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_pic',
            field=cloudinary.models.CloudinaryField(default='comments/d.png', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
