# Generated by Django 3.0 on 2022-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220117_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_pic',
            field=models.ImageField(default='comments/d.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(upload_to='blog/post_banner'),
        ),
    ]
