# Generated by Django 3.2 on 2024-01-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20230908_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='logo',
            field=models.ImageField(default='a', upload_to='work/work_logo'),
            preserve_default=False,
        ),
    ]
