# Generated by Django 3.2 on 2023-07-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230704_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_pic',
        ),
    ]
