# Generated by Django 4.2 on 2026-05-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_auto_20230908_1636"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
